name: React App CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Node.js
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Build React application
        run: npm run build