name: React App CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Node.js
        shell: powershell
        run: |
          node --version
          npm --version

      - name: Install dependencies
        shell: powershell
        run: npm install

      - name: Build React application
        shell: powershell
        run: npm run build

      - name: Deploy to NGINX
        shell: powershell
        run: |
          Remove-Item "E:\ReactTodoUIMonolith\build\*" -Recurse -Force
          Copy-Item ".\build\*" "E:\ReactTodoUIMonolith\build" -Recurse -Force